# Generated by Django 5.2.2 on 2025-06-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='plays',
            field=models.IntegerField(default=0),
        ),
    ]
