# Generated by Django 5.2.2 on 2025-06-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_quiz_plays'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.IntegerField(default=0),
        ),
    ]
