# Generated by Django 5.2.2 on 2025-06-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_quiz_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
    ]
