# Generated by Django 5.2.2 on 2025-06-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_remove_quiz_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='timeLimit',
            field=models.IntegerField(default=30),
        ),
    ]
