# Generated by Django 5.2.2 on 2025-06-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0006_question_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='timeLimit',
            new_name='time_limit',
        ),
    ]
